# Generated by Django 5.1.7 on 2025-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak_15', 'Primeira Estrela (15 dias de Streak)'), ('streak_30', 'Segunda Estrela (30 dias de Streak)'), ('streak_60', 'Terceira Estrela (60 dias de Streak)'), ('streak_100', 'Mestre dos Streaks (100 dias)'), ('events_10', 'Organizador Iniciante (10 eventos)'), ('events_25', 'Organizador Experiente (25 eventos)'), ('events_50', 'Mestre dos Eventos (50 eventos)')], max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['achievement_type'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='highest_streak',
            field=models.IntegerField(default=0, verbose_name='Maior Streak'),
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.achievement'),
        ),
    ]
